
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.4.1+9a89d02ff for .NET Framework
      Oluşturma başlatıldı: 23.02.2023 09:28:27.
      1 düğümünde "C:\\Users\\omerk\\Documents\\GitHub\\isyeriegitimi\\buildDers04\\CMakeFiles\\3.26.0-rc3\\CompilerIdC\\CompilerIdC.vcxproj" projesi (varsayılan hedefler).
      PrepareForBuild:
        "Debug\\" dizini oluşturuluyor.
        "Debug\\CompilerIdC.tlog\\" dizini oluşturuluyor.
      InitializeBuildStatus:
        "AlwaysCreate" belirtildiği için "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" oluşturuluyor.
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\omerk\\Documents\\GitHub\\isyeriegitimi\\buildDers04\\CMakeFiles\\3.26.0-rc3\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" dosyası siliniyor.
        "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate" öğesine erişiliyor.
      "C:\\Users\\omerk\\Documents\\GitHub\\isyeriegitimi\\buildDers04\\CMakeFiles\\3.26.0-rc3\\CompilerIdC\\CompilerIdC.vcxproj" Projesini Oluşturma İşlemi Tamamlandı (varsayılan hedefler).
      
      Oluşturma başarılı oldu.
          0 Uyarı
          0 Hata
      
      Geçen Süre 00:00:00.88
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/omerk/Documents/GitHub/isyeriegitimi/buildDers04/CMakeFiles/3.26.0-rc3/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.4.1+9a89d02ff for .NET Framework
      Oluşturma başlatıldı: 23.02.2023 09:28:28.
      1 düğümünde "C:\\Users\\omerk\\Documents\\GitHub\\isyeriegitimi\\buildDers04\\CMakeFiles\\3.26.0-rc3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" projesi (varsayılan hedefler).
      PrepareForBuild:
        "Debug\\" dizini oluşturuluyor.
        "Debug\\CompilerIdCXX.tlog\\" dizini oluşturuluyor.
      InitializeBuildStatus:
        "AlwaysCreate" belirtildiği için "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" oluşturuluyor.
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\omerk\\Documents\\GitHub\\isyeriegitimi\\buildDers04\\CMakeFiles\\3.26.0-rc3\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" dosyası siliniyor.
        "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate" öğesine erişiliyor.
      "C:\\Users\\omerk\\Documents\\GitHub\\isyeriegitimi\\buildDers04\\CMakeFiles\\3.26.0-rc3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" Projesini Oluşturma İşlemi Tamamlandı (varsayılan hedefler).
      
      Oluşturma başarılı oldu.
          0 Uyarı
          0 Hata
      
      Geçen Süre 00:00:00.67
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/omerk/Documents/GitHub/isyeriegitimi/buildDers04/CMakeFiles/3.26.0-rc3/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/omerk/Documents/GitHub/isyeriegitimi/buildDers04/CMakeFiles/CMakeScratch/TryCompile-a19og6"
      binary: "C:/Users/omerk/Documents/GitHub/isyeriegitimi/buildDers04/CMakeFiles/CMakeScratch/TryCompile-a19og6"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/Users/omerk/Documents/GitHub/isyeriegitimi/buildDers04/CMakeFiles/CMakeScratch/TryCompile-a19og6
        
        Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_1ea32.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && MSBuild version 17.4.1+9a89d02ff for .NET Framework
        Oluşturma başlatıldı: 23.02.2023 09:28:29.
        1 düğümünde "C:\\Users\\omerk\\Documents\\GitHub\\isyeriegitimi\\buildDers04\\CMakeFiles\\CMakeScratch\\TryCompile-a19og6\\cmTC_1ea32.vcxproj" projesi (varsayılan hedefler).
        PrepareForBuild:
          "cmTC_1ea32.dir\\Debug\\" dizini oluşturuluyor.
          "C:\\Users\\omerk\\Documents\\GitHub\\isyeriegitimi\\buildDers04\\CMakeFiles\\CMakeScratch\\TryCompile-a19og6\\Debug\\" dizini oluşturuluyor.
          "cmTC_1ea32.dir\\Debug\\cmTC_1ea32.tlog\\" dizini oluşturuluyor.
        InitializeBuildStatus:
          "AlwaysCreate" belirtildiği için "cmTC_1ea32.dir\\Debug\\cmTC_1ea32.tlog\\unsuccessfulbuild" oluşturuluyor.
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_1ea32.dir\\Debug\\\\" /Fd"cmTC_1ea32.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
          x64 için Microsoft (R) C/C++ İyileştirmeli Derleyicisi Sürüm 19.34.31942
          CMakeCCompilerABI.c
          Telif Hakkı (C) Microsoft Corporation. Tüm hakları saklıdır.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_1ea32.dir\\Debug\\\\" /Fd"cmTC_1ea32.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\omerk\\Documents\\GitHub\\isyeriegitimi\\buildDers04\\CMakeFiles\\CMakeScratch\\TryCompile-a19og6\\Debug\\cmTC_1ea32.exe" /INCREMENTAL /ILK:"cmTC_1ea32.dir\\Debug\\cmTC_1ea32.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/omerk/Documents/GitHub/isyeriegitimi/buildDers04/CMakeFiles/CMakeScratch/TryCompile-a19og6/Debug/cmTC_1ea32.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/omerk/Documents/GitHub/isyeriegitimi/buildDers04/CMakeFiles/CMakeScratch/TryCompile-a19og6/Debug/cmTC_1ea32.lib" /MACHINE:X64  /machine:x64 cmTC_1ea32.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_1ea32.vcxproj -> C:\\Users\\omerk\\Documents\\GitHub\\isyeriegitimi\\buildDers04\\CMakeFiles\\CMakeScratch\\TryCompile-a19og6\\Debug\\cmTC_1ea32.exe
        FinalizeBuildStatus:
          "cmTC_1ea32.dir\\Debug\\cmTC_1ea32.tlog\\unsuccessfulbuild" dosyası siliniyor.
          "cmTC_1ea32.dir\\Debug\\cmTC_1ea32.tlog\\cmTC_1ea32.lastbuildstate" öğesine erişiliyor.
        "C:\\Users\\omerk\\Documents\\GitHub\\isyeriegitimi\\buildDers04\\CMakeFiles\\CMakeScratch\\TryCompile-a19og6\\cmTC_1ea32.vcxproj" Projesini Oluşturma İşlemi Tamamlandı (varsayılan hedefler).
        
        Oluşturma başarılı oldu.
            0 Uyarı
            0 Hata
        
        Geçen Süre 00:00:00.55
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/omerk/Documents/GitHub/isyeriegitimi/buildDers04/CMakeFiles/CMakeScratch/TryCompile-znf3v3"
      binary: "C:/Users/omerk/Documents/GitHub/isyeriegitimi/buildDers04/CMakeFiles/CMakeScratch/TryCompile-znf3v3"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/Users/omerk/Documents/GitHub/isyeriegitimi/buildDers04/CMakeFiles/CMakeScratch/TryCompile-znf3v3
        
        Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_7697c.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && MSBuild version 17.4.1+9a89d02ff for .NET Framework
        Oluşturma başlatıldı: 23.02.2023 09:28:30.
        1 düğümünde "C:\\Users\\omerk\\Documents\\GitHub\\isyeriegitimi\\buildDers04\\CMakeFiles\\CMakeScratch\\TryCompile-znf3v3\\cmTC_7697c.vcxproj" projesi (varsayılan hedefler).
        PrepareForBuild:
          "cmTC_7697c.dir\\Debug\\" dizini oluşturuluyor.
          "C:\\Users\\omerk\\Documents\\GitHub\\isyeriegitimi\\buildDers04\\CMakeFiles\\CMakeScratch\\TryCompile-znf3v3\\Debug\\" dizini oluşturuluyor.
          "cmTC_7697c.dir\\Debug\\cmTC_7697c.tlog\\" dizini oluşturuluyor.
        InitializeBuildStatus:
          "AlwaysCreate" belirtildiği için "cmTC_7697c.dir\\Debug\\cmTC_7697c.tlog\\unsuccessfulbuild" oluşturuluyor.
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_7697c.dir\\Debug\\\\" /Fd"cmTC_7697c.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
          x64 için Microsoft (R) C/C++ İyileştirmeli Derleyicisi Sürüm 19.34.31942
          Telif Hakkı (C) Microsoft Corporation. Tüm hakları saklıdır.
          CMakeCXXCompilerABI.cpp
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_7697c.dir\\Debug\\\\" /Fd"cmTC_7697c.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\omerk\\Documents\\GitHub\\isyeriegitimi\\buildDers04\\CMakeFiles\\CMakeScratch\\TryCompile-znf3v3\\Debug\\cmTC_7697c.exe" /INCREMENTAL /ILK:"cmTC_7697c.dir\\Debug\\cmTC_7697c.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/omerk/Documents/GitHub/isyeriegitimi/buildDers04/CMakeFiles/CMakeScratch/TryCompile-znf3v3/Debug/cmTC_7697c.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/omerk/Documents/GitHub/isyeriegitimi/buildDers04/CMakeFiles/CMakeScratch/TryCompile-znf3v3/Debug/cmTC_7697c.lib" /MACHINE:X64  /machine:x64 cmTC_7697c.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_7697c.vcxproj -> C:\\Users\\omerk\\Documents\\GitHub\\isyeriegitimi\\buildDers04\\CMakeFiles\\CMakeScratch\\TryCompile-znf3v3\\Debug\\cmTC_7697c.exe
        FinalizeBuildStatus:
          "cmTC_7697c.dir\\Debug\\cmTC_7697c.tlog\\unsuccessfulbuild" dosyası siliniyor.
          "cmTC_7697c.dir\\Debug\\cmTC_7697c.tlog\\cmTC_7697c.lastbuildstate" öğesine erişiliyor.
        "C:\\Users\\omerk\\Documents\\GitHub\\isyeriegitimi\\buildDers04\\CMakeFiles\\CMakeScratch\\TryCompile-znf3v3\\cmTC_7697c.vcxproj" Projesini Oluşturma İşlemi Tamamlandı (varsayılan hedefler).
        
        Oluşturma başarılı oldu.
            0 Uyarı
            0 Hata
        
        Geçen Süre 00:00:00.55
        
      exitCode: 0
...
